export const CONSTANTS = {
  EMAILJS_API_KEY: process.env.GATSBY_EMAILJS_PUBLIC_API_KEY,
  EMAILJS_SERVICE_ID: process.env.GATSBY_EMAILJS_SERVICE_ID,
  EMAILJS_TEMPLATE_ID: process.env.GATSBY_EMAILJS_TEMPLATE_ID,
  EMAILJS_API_URL: process.env.GATSBY_EMAILJS_API_URL,
}
