const sliderData = [
  {
    id: 1,
    title: "Get Creative Every Day",
    bgUrl: "/images/slider_1.png",
    isBright: true,
    technologies: [
      { name: "html", id: 1 },
      { name: "css", id: 2 },
      { name: "javascript", id: 3 },
      { name: "gsap", id: 4 },
      { name: "react", id: 5 },
      { name: "webpack", id: 6 },
      { name: "figma", id: 7 },
    ],
    liveUrl: "https://get-creative-everyday-demo.netlify.app/",
    codeUrl: "https://github.com/PatrickInFrontEnd/get-creative-everyday-demo",
  },
  {
    id: 2,
    title: "Zdrowe Dziecko - magazine site",
    bgUrl: "/images/slider_2.png",
    isBright: false,
    technologies: [
      { name: "html", id: 1 },
      { name: "css", id: 2 },
      { name: "javascript", id: 3 },
      { name: "react", id: 4 },
      { name: "redux", id: 5 },
      { name: "gsap", id: 6 },
      { name: "webpack", id: 7 },
    ],
    liveUrl: "https://project-1-demo.netlify.app/",
    codeUrl: undefined,
  },
  {
    id: 3,
    title: "Erasmus project",
    bgUrl: "/images/slider_3.png",
    isBright: false,
    technologies: [
      { name: "html", id: 1 },
      { name: "css", id: 2 },
      { name: "javascript", id: 3 },
    ],
    liveUrl: "https://szkolenia-erasmus.org/",
    codeUrl: undefined,
  },
  {
    id: 4,
    title: "ZLP tournament",
    bgUrl: "/images/slider_4.png",
    isBright: true,
    technologies: [
      { name: "html", id: 4 },
      { name: "css", id: 5 },
      { name: "javascript", id: 6 },
      { name: "react", id: 7 },
      { name: "webpack", id: 8 },
    ],
    liveUrl: "https://zlp-tournament.netlify.app/",
    codeUrl: "https://github.com/PatrickInFrontEnd/ZLP",
  },
  {
    id: 5,
    title: "Flappy bird",
    bgUrl: "/images/slider_5.png",
    isBright: false,
    technologies: [
      { name: "html", id: 9 },
      { name: "css", id: 10 },
      { name: "javascript", id: 11 },
      { name: "webpack", id: 12 },
    ],
    liveUrl: "https://flappy-bird-jump.netlify.app/",
    codeUrl: "https://github.com/PatrickInFrontEnd/flappy-bird",
  },
]

export default sliderData
