const sliderData = [
  {
    id: 1,
    title: "Get Creative Every Day",
    bgUrl: "/images/slider/slider_1.png",
    isBright: true,
    technologies: [
      { name: "html", id: 1 },
      { name: "css", id: 2 },
      { name: "javascript", id: 3 },
      { name: "gsap", id: 4 },
      { name: "react", id: 5 },
      { name: "webpack", id: 6 },
      { name: "styled-components", id: 7 },
      { name: "figma", id: 8 },
    ],
    liveUrl: "https://get-creative-everyday-demo.netlify.app/",
    codeUrl: "https://github.com/PatrickInFrontEnd/get-creative-everyday-demo",
  },
  {
    id: 2,
    title: "Zdrowe Dziecko - magazine site",
    bgUrl: "/images/slider/slider_2.png",
    isBright: false,
    technologies: [
      { name: "html", id: 9 },
      { name: "css", id: 10 },
      { name: "javascript", id: 11 },
      { name: "gsap", id: 12 },
      { name: "react", id: 13 },
      { name: "redux", id: 14 },
      { name: "styled-components", id: 15 },
      { name: "webpack", id: 16 },
    ],
    liveUrl: "https://project-1-demo.netlify.app/",
    codeUrl: undefined,
  },
  {
    id: 3,
    title: "Erasmus project",
    bgUrl: "/images/slider/slider_3.png",
    isBright: false,
    technologies: [
      { name: "html", id: 17 },
      { name: "css", id: 18 },
      { name: "javascript", id: 19 },
    ],
    liveUrl: "https://szkolenia-erasmus.org/",
    codeUrl: undefined,
  },
  {
    id: 4,
    title: "Cybersecurity SaaS platform",
    bgUrl: "/images/slider/slider_4.webp",
    isBright: true,
    technologies: [
      { name: "html", id: 20 },
      { name: "css", id: 21 },
      { name: "javascript", id: 22 },
      { name: "typescript", id: 23 },
      { name: "react", id: 24 },
      { name: "redux", id: 25 },
      { name: "figma", id: 26 },
      { name: "webpack", id: 27 },
      { name: "firebase", id: 28 },
    ],
    liveUrl:
      "https://startup-house.com/case-studies/cyber-risk-mitigation-platform",
  },
  {
    id: 5,
    title: "Banking & Real Estate SaaS platform",
    bgUrl: "/images/slider/slider_5.png",
    isBright: true,
    technologies: [
      { name: "html", id: 29 },
      { name: "css", id: 30 },
      { name: "javascript", id: 31 },
      { name: "typescript", id: 32 },
      { name: "react", id: 33 },
      { name: "nextjs", id: 34 },
      { name: "figma", id: 35 },
      { name: "webpack", id: 36 },
    ],
  },
  {
    id: 6,
    title: "E-commerce platform for filmmakers",
    bgUrl: "/images/slider/slider_6.png",
    isBright: true,
    technologies: [
      { name: "html", id: 37 },
      { name: "css", id: 38 },
      { name: "javascript", id: 39 },
      { name: "typescript", id: 40 },
      { name: "react", id: 41 },
      { name: "nextjs", id: 42 },
      { name: "figma", id: 43 },
      { name: "webpack", id: 44 },
    ],
  },
  {
    id: 7,
    title: "Flappy bird",
    bgUrl: "/images/slider/slider_7.png",
    isBright: false,
    technologies: [
      { name: "html", id: 45 },
      { name: "css", id: 46 },
      { name: "javascript", id: 47 },
      { name: "styled-components", id: 48 },
      { name: "webpack", id: 49 },
    ],
    liveUrl: "https://flappy-bird-jump.netlify.app/",
    codeUrl: "https://github.com/PatrickInFrontEnd/flappy-bird",
  },
]

export default sliderData
